# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./SportsBar/SportsBar.sln
    - name: Build
      run: dotnet build ./SportsBar/SportsBar.sln --no-restore
    - name: Test
      run: dotnet test ./SportsBar.UnitTests/SportsBar.UnitTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=UnitTestResults.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
        files: |
          ./SportsBar.UnitTests/test-results/UnitTestResults.trx
